import { ApplicationConfig, importProvidersFrom, provideZonelessChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { HTTP_INTERCEPTORS, provideHttpClient, withInterceptorsFromDi } from '@angular/common/http';
import { JwtModule } from '@auth0/angular-jwt';
import {
  provideLucideIcons,
  LucideActivity,
  LucideAlertCircle,
  LucideAlertTriangle,
  LucideAreaChart,
  LucideBarChart3,
  LucideBookmark,
  LucideBox,
  LucideCheck,
  LucideCheckCircle,
  LucideChevronDown,
  LucideChevronRight,
  LucideCircleDashed,
  LucideClock,
  LucideCloud,
  LucideCog,
  LucideCopy,
  LucideCpu,
  LucideDatabase,
  LucideDownload,
  LucideDroplets,
  LucideEye,
  LucideEyeOff,
  LucideFilter,
  LucideFilterX,
  LucideFlame,
  LucideGauge,
  LucideGlobe,
  LucideGroup,
  LucideHardDrive,
  LucideHash,
  LucideInfo,
  LucideLayers,
  LucideLayoutGrid,
  LucideLink,
  LucideLoader2,
  LucideLogOut,
  LucideMaximize2,
  LucideMemoryStick,
  LucideMinimize2,
  LucideMinus,
  LucideMoreVertical,
  LucideNetwork,
  LucidePackage,
  LucidePalette,
  LucidePause,
  LucidePlay,
  LucidePlus,
  LucidePower,
  LucideRefreshCw,
  LucideRotateCcw,
  LucideSave,
  LucideSearch,
  LucideServer,
  LucideSettings,
  LucideShield,
  LucideSnowflake,
  LucideSparkles,
  LucideSquare,
  LucideSun,
  LucideThermometer,
  LucideTrash2,
  LucideTrendingUp,
  LucideUser,
  LucideVolume2,
  LucideVolumeX,
  LucideX,
  LucideXCircle,
  LucideZap,
  LucideZoomIn,
  LucideZoomOut,
} from '@lucide/angular';
import {
  BarController,
  BarElement,
  CategoryScale,
  Colors,
  Filler,
  Legend,
  LineController,
  LineElement,
  LinearScale,
  PointElement,
} from 'chart.js';
import { provideCharts } from 'ng2-charts';
import { environment } from '../environments/environment';
import { JwtInterceptor } from './_services/jwt-interceptor';
import { routes } from './app.routes';

export function tokenGetter() {
  return localStorage.getItem('authToken');
}

export const appConfig: ApplicationConfig = {
  providers: [
    provideZonelessChangeDetection(),
    provideHttpClient(withInterceptorsFromDi()),
    provideRouter(routes),
    {
      provide: HTTP_INTERCEPTORS,
      useClass: JwtInterceptor,
      multi: true,
    },
    provideCharts({
      registerables: [
        BarController,
        LineController,
        Legend,
        Colors,
        CategoryScale,
        LinearScale,
        BarElement,
        LineElement,
        PointElement,
        Filler,
      ],
    }),
    importProvidersFrom(
      JwtModule.forRoot({
        config: {
          tokenGetter,
          allowedDomains: undefined,
          disallowedRoutes: [`${environment.apiUrl}/api/auth/login`],
        },
      })
    ),
    provideLucideIcons(
      LucideActivity,
      LucideAlertCircle,
      LucideAlertTriangle,
      LucideAreaChart,
      LucideBarChart3,
      LucideBookmark,
      LucideBox,
      LucideCheck,
      LucideCheckCircle,
      LucideChevronDown,
      LucideChevronRight,
      LucideCircleDashed,
      LucideClock,
      LucideCloud,
      LucideCog,
      LucideCopy,
      LucideCpu,
      LucideDatabase,
      LucideDownload,
      LucideDroplets,
      LucideEye,
      LucideEyeOff,
      LucideFilter,
      LucideFilterX,
      LucideFlame,
      LucideGauge,
      LucideGlobe,
      LucideGroup,
      LucideHardDrive,
      LucideHash,
      LucideInfo,
      LucideLayers,
      LucideLayoutGrid,
      LucideLink,
      LucideLoader2,
      LucideLogOut,
      LucideMaximize2,
      LucideMemoryStick,
      LucideMinimize2,
      LucideMinus,
      LucideMoreVertical,
      LucideNetwork,
      LucidePackage,
      LucidePalette,
      LucidePause,
      LucidePlay,
      LucidePlus,
      LucidePower,
      LucideRefreshCw,
      LucideRotateCcw,
      LucideSave,
      LucideSearch,
      LucideServer,
      LucideSettings,
      LucideShield,
      LucideSnowflake,
      LucideSparkles,
      LucideSquare,
      LucideSun,
      LucideThermometer,
      LucideTrash2,
      LucideTrendingUp,
      LucideUser,
      LucideVolume2,
      LucideVolumeX,
      LucideX,
      LucideXCircle,
      LucideZap,
      LucideZoomIn,
      LucideZoomOut,
    ),
  ],
};
